### ISSUE TITLE
有使用文档吗？你这个和java版的有点不一样吧？secretKey是用来干什么的？

### ISSUE THREAD

**Issue by Rebellioncry** [TestsLing/aj-captcha-go#9]

**Comment by TestsLing** [comment]
和java版本基本一样的，大同小异吧， secretKey 是用来做数据加密和解密的

**Comment by TestsLing** [comment]
readme即使用文档

**Comment by Rebellioncry** [comment]
@TestsLing ok我懂了，好像是java版里的前端示例文档没有更新，我试了你这个能直接和java版对接的

**Comment by Rebellioncry** [comment]
@TestsLing 我觉得你应该把请求实体和返回实体写一下，好像代码里都是用map，我都不知道里面的key是什么，得自己进代码调，就比如factory.GetService().Get()里的返回是用map，我得调试才知道里面是什么

**Comment by TestsLing** [comment]
> 

是的，这确实是个问题，感谢提出

**Comment by TestsLing** [comment]
是的，这确实是个问题，感谢提出

**Comment by TestsLing** [comment]
是的，这确实是个问题，感谢提出 @Rebellioncry
